// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/ignata/go-microservices-boilerplate/internal/product/dto"
	mock "github.com/stretchr/testify/mock"
)

// ProductUseCase is an autogenerated mock type for the ProductUseCase type
type ProductUseCase struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, req
func (_m *ProductUseCase) CreateProduct(ctx context.Context, req *dto.CreateProductRequest) (*dto.ProductResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *dto.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateProductRequest) (*dto.ProductResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateProductRequest) *dto.ProductResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateProductRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: ctx, req
func (_m *ProductUseCase) DeleteProduct(ctx context.Context, req *dto.DeleteProductRequest) (*dto.DeleteResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 *dto.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteProductRequest) (*dto.DeleteResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.DeleteProductRequest) *dto.DeleteResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.DeleteProductRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProduct provides a mock function with given fields: ctx, req
func (_m *ProductUseCase) GetProduct(ctx context.Context, req *dto.GetProductRequest) (*dto.ProductResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *dto.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetProductRequest) (*dto.ProductResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetProductRequest) *dto.ProductResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetProductRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProducts provides a mock function with given fields: ctx, req
func (_m *ProductUseCase) ListProducts(ctx context.Context, req *dto.ListProductsRequest) (*dto.ProductListResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 *dto.ProductListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListProductsRequest) (*dto.ProductListResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListProductsRequest) *dto.ProductListResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ListProductsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreProduct provides a mock function with given fields: ctx, req
func (_m *ProductUseCase) RestoreProduct(ctx context.Context, req *dto.RestoreProductRequest) (*dto.ProductResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RestoreProduct")
	}

	var r0 *dto.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RestoreProductRequest) (*dto.ProductResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RestoreProductRequest) *dto.ProductResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.RestoreProductRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, productID, req
func (_m *ProductUseCase) UpdateProduct(ctx context.Context, productID string, req *dto.UpdateProductRequest) (*dto.ProductResponse, error) {
	ret := _m.Called(ctx, productID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *dto.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateProductRequest) (*dto.ProductResponse, error)); ok {
		return rf(ctx, productID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.UpdateProductRequest) *dto.ProductResponse); ok {
		r0 = rf(ctx, productID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.UpdateProductRequest) error); ok {
		r1 = rf(ctx, productID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStock provides a mock function with given fields: ctx, req
func (_m *ProductUseCase) UpdateStock(ctx context.Context, req *dto.UpdateStockRequest) (*dto.UpdateStockResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStock")
	}

	var r0 *dto.UpdateStockResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateStockRequest) (*dto.UpdateStockResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateStockRequest) *dto.UpdateStockResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UpdateStockResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.UpdateStockRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductUseCase creates a new instance of ProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductUseCase {
	mock := &ProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
